Venkataramanaiah_Thushar_HW.txt

added folder structure for Venkataramanaiah_Thushar homework 1

Added Folder Structure for Venkataramanaiah_Thushar homework 1

---

Babu_Ashvath/hw1/Babu_hw1.txt

Ashvath's Pull request, created folder

Added folder structure for Ashvath homeworks

---

Tud_Nicci/hw1/Tud_HW.txt

created folder for HW1, testing pull request

Added folder structure for Nicci Tud homework 1

---

Bandila_Mara-Teodora/hw1/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw10/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw11/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw12/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw2/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw3/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw4/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw5/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw6/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw7/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw8/Bandila_Mara-Teodora_HW.txt
Bandila_Mara-Teodora/hw9/Bandila_Mara-Teodora_HW.txt

Added folder structure for homeworks for Mara-Teodora Bandila

Added folder structure for homeworks for Mara-Teodora Bandila

---

Orlaineta_Mateo/hw1/Alice_HW.txt

Added folder structure for Alice homework 1

Orlaineta_Mateo_hw1

---

Venkataramanaiah_Thushar/hw1/And.hdl
Venkataramanaiah_Thushar/hw1/And16.hdl
Venkataramanaiah_Thushar/hw1/DMux.hdl
Venkataramanaiah_Thushar/hw1/DMux4Way.hdl
Venkataramanaiah_Thushar/hw1/DMux8Way.hdl
Venkataramanaiah_Thushar/hw1/Mux.hdl
Venkataramanaiah_Thushar/hw1/Mux16.hdl
Venkataramanaiah_Thushar/hw1/Mux4Way16.hdl
Venkataramanaiah_Thushar/hw1/Mux8Way16.hdl
Venkataramanaiah_Thushar/hw1/Not.hdl
Venkataramanaiah_Thushar/hw1/Not16.hdl
Venkataramanaiah_Thushar/hw1/Or.hdl
Venkataramanaiah_Thushar/hw1/Or16.hdl
Venkataramanaiah_Thushar/hw1/Or8Way.hdl
Venkataramanaiah_Thushar/hw1/Xor.hdl
thushar_hw.txt

Added folder structure for Thushar homework 1

Venkataramanaiah_Thushar_hw1

---

Belachew_Robera/hw1/And.hdl
Belachew_Robera/hw1/And16.hdl
Belachew_Robera/hw1/Belachew_HW1.txt
Belachew_Robera/hw1/DMux.hdl
Belachew_Robera/hw1/DMux4Way.hdl
Belachew_Robera/hw1/DMux8Way.hdl
Belachew_Robera/hw1/Mux.hdl
Belachew_Robera/hw1/Mux16.hdl
Belachew_Robera/hw1/Mux4Way16.hdl
Belachew_Robera/hw1/Mux8Way16.hdl
Belachew_Robera/hw1/Not.hdl
Belachew_Robera/hw1/Not16.hdl
Belachew_Robera/hw1/Or.hdl
Belachew_Robera/hw1/Or16.hdl
Belachew_Robera/hw1/Or8Way.hdl
Belachew_Robera/hw1/Xor.hdl

Added folder structure for Robera Belachew homework 1

Belachew_Robera_hw1

---

Assaf_Aly-Mansour-Aly-Mohamed/hw1/And.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/And16.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/DMux.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/DMux4Way.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/DMux8Way.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/Mux.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/Mux16.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/Mux4Way16.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/Mux8Way16.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/Not.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/Not16.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/Or.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/Or16.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/Or8Way.hdl
Assaf_Aly-Mansour-Aly-Mohamed/hw1/Xor.hdl

Assaf_Aly-Mansour-Aly-Mohamed_hw1

---

Tud_Nicci/hw1/And.hdl
Tud_Nicci/hw1/And16.hdl
Tud_Nicci/hw1/DMux.hdl
Tud_Nicci/hw1/DMux4Way.hdl
Tud_Nicci/hw1/DMux8Way.hdl
Tud_Nicci/hw1/Mux.hdl
Tud_Nicci/hw1/Mux16.hdl
Tud_Nicci/hw1/Mux4Way16.hdl
Tud_Nicci/hw1/Mux8Way16.hdl
Tud_Nicci/hw1/Not.hdl
Tud_Nicci/hw1/Not16.hdl
Tud_Nicci/hw1/Or.hdl
Tud_Nicci/hw1/Or16.hdl
Tud_Nicci/hw1/Or8Way.hdl
Tud_Nicci/hw1/Xor.hdl

Pull request for added HDL files for hw1

Tud_Nicci_hw1

---

Mersini_Kiara/hw1/And.hdl
Mersini_Kiara/hw1/And16.hdl
Mersini_Kiara/hw1/DMux.hdl
Mersini_Kiara/hw1/DMux4Way.hdl
Mersini_Kiara/hw1/DMux8Way.hdl
Mersini_Kiara/hw1/Mux.hdl
Mersini_Kiara/hw1/Mux16.hdl
Mersini_Kiara/hw1/Mux4Way16.hdl
Mersini_Kiara/hw1/Mux8Way16.hdl
Mersini_Kiara/hw1/Not.hdl
Mersini_Kiara/hw1/Not16.hdl
Mersini_Kiara/hw1/Or.hdl
Mersini_Kiara/hw1/Or16.hdl
Mersini_Kiara/hw1/Or8Way.hdl
Mersini_Kiara/hw1/Xor.hdl
kiara_HW.txt

added folder structure for kiara homework 1

Mersini_Kiara_hw1

---

Mata_Anxhela/hw1/And.hdl
Mata_Anxhela/hw1/And16.hdl
Mata_Anxhela/hw1/DMux.hdl
Mata_Anxhela/hw1/DMux4Way.hdl
Mata_Anxhela/hw1/DMux8Way.hdl
Mata_Anxhela/hw1/Mux.hdl
Mata_Anxhela/hw1/Mux16.hdl
Mata_Anxhela/hw1/Mux4Way16.hdl
Mata_Anxhela/hw1/Mux8Way16.hdl
Mata_Anxhela/hw1/Not.hdl
Mata_Anxhela/hw1/Not16.hdl
Mata_Anxhela/hw1/Or.hdl
Mata_Anxhela/hw1/Or16.hdl
Mata_Anxhela/hw1/Or8Way.hdl
Mata_Anxhela/hw1/Xor.hdl
anxhela_mata.txt

added folder structure for anxhela homework 1

Mata_Anxhela_hw1

---

Staykova_Margarita/hw1/And.hdl
Staykova_Margarita/hw1/And16.hdl
Staykova_Margarita/hw1/DMux.hdl
Staykova_Margarita/hw1/DMux4Way.hdl
Staykova_Margarita/hw1/DMux8Way.hdl
Staykova_Margarita/hw1/Mux.hdl
Staykova_Margarita/hw1/Mux16.hdl
Staykova_Margarita/hw1/Mux4Way16.hdl
Staykova_Margarita/hw1/Mux8Way16.hdl
Staykova_Margarita/hw1/Not.hdl
Staykova_Margarita/hw1/Not16.hdl
Staykova_Margarita/hw1/Or.hdl
Staykova_Margarita/hw1/Or16.hdl
Staykova_Margarita/hw1/Or8Way.hdl
Staykova_Margarita/hw1/Xor.hdl
margo_HW.txt

Added folder structure for Margarita homework 1

Staykova_Margarita_hw1

---

Cao_Yiheng/hw1/And.hdl
Cao_Yiheng/hw1/And16.hdl
Cao_Yiheng/hw1/DMux.hdl
Cao_Yiheng/hw1/DMux4Way.hdl
Cao_Yiheng/hw1/DMux8Way.hdl
Cao_Yiheng/hw1/Mux.hdl
Cao_Yiheng/hw1/Mux16.hdl
Cao_Yiheng/hw1/Mux4Way16.hdl
Cao_Yiheng/hw1/Mux8Way16.hdl
Cao_Yiheng/hw1/Not.hdl
Cao_Yiheng/hw1/Not16.hdl
Cao_Yiheng/hw1/Or.hdl
Cao_Yiheng/hw1/Or16.hdl
Cao_Yiheng/hw1/Or8Way.hdl
Cao_Yiheng/hw1/Xor.hdl

Add all HDL files for homework 1

Cao_Yiheng_hw1

---

Burduli_Nikoloz/hw1/And.hdl
Burduli_Nikoloz/hw1/And16.hdl
Burduli_Nikoloz/hw1/DMux.hdl
Burduli_Nikoloz/hw1/DMux4Way.hdl
Burduli_Nikoloz/hw1/DMux8Way.hdl
Burduli_Nikoloz/hw1/Mux.hdl
Burduli_Nikoloz/hw1/Mux16.hdl
Burduli_Nikoloz/hw1/Mux4Way16.hdl
Burduli_Nikoloz/hw1/Mux8Way16.hdl
Burduli_Nikoloz/hw1/Not.hdl
Burduli_Nikoloz/hw1/Not16.hdl
Burduli_Nikoloz/hw1/Or.hdl
Burduli_Nikoloz/hw1/Or16.hdl
Burduli_Nikoloz/hw1/Or8Way.hdl
Burduli_Nikoloz/hw1/Xor.hdl
niko_hw.txt

Added folder structure for nikoloz homework 1

Burduli_Nikoloz_hw1

---

Schwentor_Zachary/hw1/And.hdl
Schwentor_Zachary/hw1/And16.hdl
Schwentor_Zachary/hw1/DMux.hdl
Schwentor_Zachary/hw1/DMux4Way.hdl
Schwentor_Zachary/hw1/DMux8Way.hdl
Schwentor_Zachary/hw1/Mux.hdl
Schwentor_Zachary/hw1/Mux16.hdl
Schwentor_Zachary/hw1/Mux4Way16.hdl
Schwentor_Zachary/hw1/Mux8Way16.hdl
Schwentor_Zachary/hw1/Not.hdl
Schwentor_Zachary/hw1/Not16.hdl
Schwentor_Zachary/hw1/Or.hdl
Schwentor_Zachary/hw1/Or16.hdl
Schwentor_Zachary/hw1/Or8Way.hdl
Schwentor_Zachary/hw1/Xor.hdl

Solved all homework 1 problems

Schwentor_Zachary_hw1

---

Khanmammadli_Yusif/hw1/And.hdl
Khanmammadli_Yusif/hw1/And16.hdl
Khanmammadli_Yusif/hw1/DMux.hdl
Khanmammadli_Yusif/hw1/DMux4Way.hdl
Khanmammadli_Yusif/hw1/DMux8Way.hdl
Khanmammadli_Yusif/hw1/Mux.hdl
Khanmammadli_Yusif/hw1/Mux16.hdl
Khanmammadli_Yusif/hw1/Mux4Way16.hdl
Khanmammadli_Yusif/hw1/Mux8Way16.hdl
Khanmammadli_Yusif/hw1/Not.hdl
Khanmammadli_Yusif/hw1/Not16.hdl
Khanmammadli_Yusif/hw1/Or.hdl
Khanmammadli_Yusif/hw1/Or16.hdl
Khanmammadli_Yusif/hw1/Or8Way.hdl
Khanmammadli_Yusif/hw1/Xor.hdl

Khanmammadli_Yusif_hw1

---

Iranmanesh_Amirali/hw1/And.hdl
Iranmanesh_Amirali/hw1/And16.hdl
Iranmanesh_Amirali/hw1/DMux.hdl
Iranmanesh_Amirali/hw1/DMux4Way.hdl
Iranmanesh_Amirali/hw1/DMux8Way.hdl
Iranmanesh_Amirali/hw1/Mux.hdl
Iranmanesh_Amirali/hw1/Mux16.hdl
Iranmanesh_Amirali/hw1/Mux4Way16.hdl
Iranmanesh_Amirali/hw1/Mux8Way16.hdl
Iranmanesh_Amirali/hw1/Not.hdl
Iranmanesh_Amirali/hw1/Not16.hdl
Iranmanesh_Amirali/hw1/Or.hdl
Iranmanesh_Amirali/hw1/Or16.hdl
Iranmanesh_Amirali/hw1/Or8Way.hdl
Iranmanesh_Amirali/hw1/Xor.hdl

Completed hw1, implementing logic gates in HDL

Iranmanesh_Amirali_hw1

---

Yolchiyev_Mubariz/hw1.txt
Yolchiyev_Mubariz/hw1/And.hdl
Yolchiyev_Mubariz/hw1/And16.hdl
Yolchiyev_Mubariz/hw1/DMux.hdl
Yolchiyev_Mubariz/hw1/DMux4Way.hdl
Yolchiyev_Mubariz/hw1/DMux8Way.hdl
Yolchiyev_Mubariz/hw1/Mux.hdl
Yolchiyev_Mubariz/hw1/Mux16.hdl
Yolchiyev_Mubariz/hw1/Mux4Way16.hdl
Yolchiyev_Mubariz/hw1/Mux8Way16.hdl
Yolchiyev_Mubariz/hw1/Not.hdl
Yolchiyev_Mubariz/hw1/Not16.hdl
Yolchiyev_Mubariz/hw1/Or.hdl
Yolchiyev_Mubariz/hw1/Or16.hdl
Yolchiyev_Mubariz/hw1/Or8Way.hdl
Yolchiyev_Mubariz/hw1/Xor.hdl

Added the hw1 folder with the .hdl files. Removed the redundant txt file. Hoping the pull request will work.

Yolchiyev_Mubariz_hw1

---

Tafani_Anja/hw1/And.hdl
Tafani_Anja/hw1/And16.hdl
Tafani_Anja/hw1/DMux.hdl
Tafani_Anja/hw1/DMux4Way.hdl
Tafani_Anja/hw1/DMux8Way.hdl
Tafani_Anja/hw1/Mux.hdl
Tafani_Anja/hw1/Mux16.hdl
Tafani_Anja/hw1/Mux4Way16.hdl
Tafani_Anja/hw1/Mux8Way16.hdl
Tafani_Anja/hw1/Not.hdl
Tafani_Anja/hw1/Not16.hdl
Tafani_Anja/hw1/Or.hdl
Tafani_Anja/hw1/Or16.hdl
Tafani_Anja/hw1/Or8Way.hdl
Tafani_Anja/hw1/Xor.hdl

added folder structure to anja homework 1

Tafani_Anja_hw1

---

ValdezCastro_AlexisLeonel/hw1/And.hdl
ValdezCastro_AlexisLeonel/hw1/And16.hdl
ValdezCastro_AlexisLeonel/hw1/DMux.hdl
ValdezCastro_AlexisLeonel/hw1/DMux4Way.hdl
ValdezCastro_AlexisLeonel/hw1/DMux8Way.hdl
ValdezCastro_AlexisLeonel/hw1/Mux.hdl
ValdezCastro_AlexisLeonel/hw1/Mux16.hdl
ValdezCastro_AlexisLeonel/hw1/Mux4Way16.hdl
ValdezCastro_AlexisLeonel/hw1/Mux8Way16.hdl
ValdezCastro_AlexisLeonel/hw1/Not.hdl
ValdezCastro_AlexisLeonel/hw1/Not16.hdl
ValdezCastro_AlexisLeonel/hw1/Or.hdl
ValdezCastro_AlexisLeonel/hw1/Or16.hdl
ValdezCastro_AlexisLeonel/hw1/Or8Way.hdl
ValdezCastro_AlexisLeonel/hw1/Xor.hdl

ValdezCastro_AlexisLeonel_hw1

---

Huseynli_Valeh.txt
Huseynli_Valeh/hw1/And.hdl
Huseynli_Valeh/hw1/And16.hdl
Huseynli_Valeh/hw1/DMux.hdl
Huseynli_Valeh/hw1/DMux4Way.hdl
Huseynli_Valeh/hw1/DMux8Way.hdl
Huseynli_Valeh/hw1/Mux.hdl
Huseynli_Valeh/hw1/Mux16.hdl
Huseynli_Valeh/hw1/Mux4Way16.hdl
Huseynli_Valeh/hw1/Mux8Way16.hdl
Huseynli_Valeh/hw1/Not.hdl
Huseynli_Valeh/hw1/Not16.hdl
Huseynli_Valeh/hw1/Or.hdl
Huseynli_Valeh/hw1/Or16.hdl
Huseynli_Valeh/hw1/Or8Way.hdl
Huseynli_Valeh/hw1/Xor.hdl

Huseynli_Valeh_hw1

---

Khaburzania_Saba/hw1/And.hdl
Khaburzania_Saba/hw1/And16.hdl
Khaburzania_Saba/hw1/DMux.hdl
Khaburzania_Saba/hw1/DMux4Way.hdl
Khaburzania_Saba/hw1/DMux8Way.hdl
Khaburzania_Saba/hw1/Mux.hdl
Khaburzania_Saba/hw1/Mux16.hdl
Khaburzania_Saba/hw1/Mux4Way16.hdl
Khaburzania_Saba/hw1/Mux8Way16.hdl
Khaburzania_Saba/hw1/Not.hdl
Khaburzania_Saba/hw1/Not16.hdl
Khaburzania_Saba/hw1/Or.hdl
Khaburzania_Saba/hw1/Or16.hdl
Khaburzania_Saba/hw1/Or8Way.hdl
Khaburzania_Saba/hw1/Xor.hdl
saba_hw.txt

added folder structure for saba homework 1

Khaburzania_Saba_hw1

---

Kalemasi_Lend/hw1/And.hdl
Kalemasi_Lend/hw1/And16.hdl
Kalemasi_Lend/hw1/DMux.hdl
Kalemasi_Lend/hw1/DMux4Way.hdl
Kalemasi_Lend/hw1/DMux8Way.hdl
Kalemasi_Lend/hw1/Mux.hdl
Kalemasi_Lend/hw1/Mux16.hdl
Kalemasi_Lend/hw1/Mux4Way16.hdl
Kalemasi_Lend/hw1/Mux8Way16.hdl
Kalemasi_Lend/hw1/Not.hdl
Kalemasi_Lend/hw1/Not16.hdl
Kalemasi_Lend/hw1/Or.hdl
Kalemasi_Lend/hw1/Or16.hdl
Kalemasi_Lend/hw1/Or8Way.hdl
Kalemasi_Lend/hw1/Xor.hdl

Kalemasi_Lend_hw1

---

Sarka_Yilikal/hw1/And.hdl
Sarka_Yilikal/hw1/And16.hdl
Sarka_Yilikal/hw1/DMux.hdl
Sarka_Yilikal/hw1/DMux4Way.hdl
Sarka_Yilikal/hw1/DMux8Way.hdl
Sarka_Yilikal/hw1/Mux.hdl
Sarka_Yilikal/hw1/Mux16.hdl
Sarka_Yilikal/hw1/Mux4Way16.hdl
Sarka_Yilikal/hw1/Mux8Way16.hdl
Sarka_Yilikal/hw1/Not.hdl
Sarka_Yilikal/hw1/Not16.hdl
Sarka_Yilikal/hw1/Or.hdl
Sarka_Yilikal/hw1/Or16.hdl
Sarka_Yilikal/hw1/Or8Way.hdl
Sarka_Yilikal/hw1/Xor.hdl

Sarka_Yilikal_hw1

---

Khanmammadli_Yusif/hw2/ALU.hdl
Khanmammadli_Yusif/hw2/Add16.hdl
Khanmammadli_Yusif/hw2/FullAdder.hdl
Khanmammadli_Yusif/hw2/HalfAdder.hdl
Khanmammadli_Yusif/hw2/Inc16.hdl

Khanmammadli_Yusif_hw2

---

Moldoveanu_Stefan/hw1/And.hdl
Moldoveanu_Stefan/hw1/And16.hdl
Moldoveanu_Stefan/hw1/DMux.hdl
Moldoveanu_Stefan/hw1/DMux4Way.hdl
Moldoveanu_Stefan/hw1/DMux8Way.hdl
Moldoveanu_Stefan/hw1/Mux.hdl
Moldoveanu_Stefan/hw1/Mux16.hdl
Moldoveanu_Stefan/hw1/Mux4Way16.hdl
Moldoveanu_Stefan/hw1/Mux8Way16.hdl
Moldoveanu_Stefan/hw1/Not.hdl
Moldoveanu_Stefan/hw1/Not16.hdl
Moldoveanu_Stefan/hw1/Or.hdl
Moldoveanu_Stefan/hw1/Or16.hdl
Moldoveanu_Stefan/hw1/Or8Way.hdl
Moldoveanu_Stefan/hw1/Stefan_HW.txt
Moldoveanu_Stefan/hw1/Xor.hdl
Moldoveanu_Stefan/hw2/ALU.hdl
Moldoveanu_Stefan/hw2/Add16.hdl
Moldoveanu_Stefan/hw2/FullAdder.hdl
Moldoveanu_Stefan/hw2/HalfAdder.hdl
Moldoveanu_Stefan/hw2/Inc16.hdl

Moldoveanu_Stefan_hw2

---

Bhave_Aneesh/hw2/ALU.hdl
Bhave_Aneesh/hw2/Add16.hdl
Bhave_Aneesh/hw2/FullAdder.hdl
Bhave_Aneesh/hw2/HalfAdder.hdl
Bhave_Aneesh/hw2/Inc16.hdl

Bhave_Aneesh_hw2

---

Okumus_Kaan/hw2/ALU.hdl
Okumus_Kaan/hw2/Add16.hdl
Okumus_Kaan/hw2/FullAdder.hdl
Okumus_Kaan/hw2/HalfAdder.hdl
Okumus_Kaan/hw2/Inc16.hdl

Okumus_Kaan submitting homework 2

Okumus_Kaan_hw2

---

Treshcheva_Olesia/hw2/ALU.hdl
Treshcheva_Olesia/hw2/Add16.hdl
Treshcheva_Olesia/hw2/FullAdder.hdl
Treshcheva_Olesia/hw2/HalfAdder.hdl
Treshcheva_Olesia/hw2/Inc16.hdl

Treshcheva_Olesia_hw2

---

Moldovan_Luca/hw2/ALU.hdl
Moldovan_Luca/hw2/Add16.hdl
Moldovan_Luca/hw2/FullAdder.hdl
Moldovan_Luca/hw2/HalfAdder.hdl
Moldovan_Luca/hw2/Inc16.hdl

Moldovan_Luca_hw2

---

Huseynli_Valeh/hw2/ALU.hdl
Huseynli_Valeh/hw2/Add16.hdl
Huseynli_Valeh/hw2/FullAdder.hdl
Huseynli_Valeh/hw2/HalfAdder.hdl
Huseynli_Valeh/hw2/Inc16.hdl

Huseynli_Valeh_hw2

---

Iranmanesh_Amirali/hw2/ALU.hdl
Iranmanesh_Amirali/hw2/Add16.hdl
Iranmanesh_Amirali/hw2/FullAdder.hdl
Iranmanesh_Amirali/hw2/HalfAdder.hdl
Iranmanesh_Amirali/hw2/Inc16.hdl

Added hw2 - Iranmanesh Amirali

Iranmanesh_Amirali_hw2

---

Yolchiyev_Mubariz/hw2/ALU.hdl
Yolchiyev_Mubariz/hw2/Add16.hdl
Yolchiyev_Mubariz/hw2/FullAdder.hdl
Yolchiyev_Mubariz/hw2/HalfAdder.hdl
Yolchiyev_Mubariz/hw2/Inc16.hdl

Yolchiyev_Mubariz_hw2

---

ValdezCastro_AlexisLeonel/hw2/ALU.hdl
ValdezCastro_AlexisLeonel/hw2/Add16.hdl
ValdezCastro_AlexisLeonel/hw2/FullAdder.hdl
ValdezCastro_AlexisLeonel/hw2/HalfAdder.hdl
ValdezCastro_AlexisLeonel/hw2/Inc16.hdl

ValdezCastro_AlexisLeonel_hw2

---

Bhave_Aneesh/hw3/Bit.hdl
Bhave_Aneesh/hw3/PC.hdl
Bhave_Aneesh/hw3/RAM16K.hdl
Bhave_Aneesh/hw3/RAM4K.hdl
Bhave_Aneesh/hw3/RAM512.hdl
Bhave_Aneesh/hw3/RAM64.hdl
Bhave_Aneesh/hw3/RAM8.hdl
Bhave_Aneesh/hw3/Register.hdl

Bhave_Aneesh_hw3

---

Khurram_Mohammad-Abdullah/hw1/And.hdl
Khurram_Mohammad-Abdullah/hw1/And16.hdl
Khurram_Mohammad-Abdullah/hw1/DMux.hdl
Khurram_Mohammad-Abdullah/hw1/DMux4Way.hdl
Khurram_Mohammad-Abdullah/hw1/DMux8Way.hdl
Khurram_Mohammad-Abdullah/hw1/Mux.hdl
Khurram_Mohammad-Abdullah/hw1/Mux16.hdl
Khurram_Mohammad-Abdullah/hw1/Mux4Way16.hdl
Khurram_Mohammad-Abdullah/hw1/Mux8Way16.hdl
Khurram_Mohammad-Abdullah/hw1/Not.hdl
Khurram_Mohammad-Abdullah/hw1/Not16.hdl
Khurram_Mohammad-Abdullah/hw1/Or.hdl
Khurram_Mohammad-Abdullah/hw1/Or16.hdl
Khurram_Mohammad-Abdullah/hw1/Or8Way.hdl
Khurram_Mohammad-Abdullah/hw1/Xor.hdl

Submitting the homework again. Did the whole process all again. If there are any issues please let me know. Thank you!

Khurram_Mohammad-Abdullah_hw1

---

Khurram_Mohammad-Abdullah/hw2/ALU.hdl
Khurram_Mohammad-Abdullah/hw2/Add16.hdl
Khurram_Mohammad-Abdullah/hw2/FullAdder.hdl
Khurram_Mohammad-Abdullah/hw2/HalfAdder.hdl
Khurram_Mohammad-Abdullah/hw2/Inc16.hdl

Submitting the homework again. Did the whole process all again. If there are any issues please let me know. Thank you!

Khurram_Mohammad-Abdullah_hw2

---

Murodjonov_Izzatbek/hw2/ALU.hdl
Murodjonov_Izzatbek/hw2/Add16.hdl
Murodjonov_Izzatbek/hw2/FullAdder.hdl
Murodjonov_Izzatbek/hw2/Inc16.hdl
Murodjonov_Izzatbek/hw2/half adder.hdl

Reuploading my hw2 with Ubaid Rehmans request

Murodjonov_Izzatbek_hw2

---

Belachew_Robera/hw3/Bit.hdl
Belachew_Robera/hw3/PC.hdl
Belachew_Robera/hw3/RAM16K.hdl
Belachew_Robera/hw3/RAM4K.hdl
Belachew_Robera/hw3/RAM512.hdl
Belachew_Robera/hw3/RAM64.hdl
Belachew_Robera/hw3/RAM8.hdl
Belachew_Robera/hw3/Register.hdl

Added new files for homework 3

Belachew_Robera_hw3

---

Moldovan_Luca/hw3/Bit.hdl
Moldovan_Luca/hw3/PC.hdl
Moldovan_Luca/hw3/RAM16K.hdl
Moldovan_Luca/hw3/RAM4K.hdl
Moldovan_Luca/hw3/RAM512.hdl
Moldovan_Luca/hw3/RAM64.hdl
Moldovan_Luca/hw3/RAM8.hdl
Moldovan_Luca/hw3/Register.hdl

Moldovan_Luca_hw3

---

Zherebilov_Rostislav/hw3/Bit.hdl
Zherebilov_Rostislav/hw3/PC.hdl
Zherebilov_Rostislav/hw3/RAM16K.hdl
Zherebilov_Rostislav/hw3/RAM4K.hdl
Zherebilov_Rostislav/hw3/RAM512.hdl
Zherebilov_Rostislav/hw3/RAM64.hdl
Zherebilov_Rostislav/hw3/RAM8.hdl
Zherebilov_Rostislav/hw3/Register.hdl

Added files for homework 3.
I will re-post my comment from my first pull request, where you run the check after the deadline, so i could not fix my compilation mistake in time in order for ANY of my first homework to get uploaded. I hope you will bring attention to this matter, since it concerns a lot of students, if not all of them.
I quoting:
Then will it be possible for me to delete the faulty file to get at least some points for the ones that were not changed after the deadline?
How am I supposed to not fail the course if I can only get either 100% for the homework or 0% if I make even a single mistake? I do not really think this is as fair as it should be for academic achievement. Especially since the way things are right now with access rules on the main repository, and the nature …

Zherebilov_Rostislav_hw3

---

Ibrahim_Joshua/hw3/Bit.hdl
Ibrahim_Joshua/hw3/PC.hdl
Ibrahim_Joshua/hw3/RAM16K.hdl
Ibrahim_Joshua/hw3/RAM4K.hdl
Ibrahim_Joshua/hw3/RAM512.hdl
Ibrahim_Joshua/hw3/RAM64.hdl
Ibrahim_Joshua/hw3/RAM8.hdl
Ibrahim_Joshua/hw3/Register.hdl

Joshua Joseph Ragy Ibrahim HW 3

Ibrahim_Joshua_hw3

---

Rada_Ylli/hw1/And.hdl
Rada_Ylli/hw1/And16.hdl
Rada_Ylli/hw1/DMux.hdl
Rada_Ylli/hw1/DMux4Way.hdl
Rada_Ylli/hw1/DMux8Way.hdl
Rada_Ylli/hw1/Mux.hdl
Rada_Ylli/hw1/Mux16.hdl
Rada_Ylli/hw1/Mux4Way16.hdl
Rada_Ylli/hw1/Mux8Way16.hdl
Rada_Ylli/hw1/Not.hdl
Rada_Ylli/hw1/Not16.hdl
Rada_Ylli/hw1/Or.hdl
Rada_Ylli/hw1/Or16.hdl
Rada_Ylli/hw1/Or8Way.hdl
Rada_Ylli/hw1/Xor.hdl

Subject: Submission of Homework 1 – New Pull Request Due to Technical Issues
Dear Professor,
I hope you are doing well. I wanted to inform you that I have submitted my Homework 1 HDL files and explain why I had to create a new pull request, despite your instruction to avoid doing so unless absolutely necessary.
Initially, I opened a pull request from my main branch, but due to some mistakes in my submission, the merge attempt failed. To resolve this, I wiped my main branch clean, synced it with the public repository, and then created a new branch, hw1, where I correctly placed all my homework files under:
Rada_Ylli/hw1/
However, when I revisited my original pull request, I found that it had automatically closed because GitHub detected that there were no changes left to commit (since main …

Rada_Ylli_hw1

---

Chen_Tianyang/hw3/Bit.hdl
Chen_Tianyang/hw3/PC.hdl
Chen_Tianyang/hw3/RAM16K.hdl
Chen_Tianyang/hw3/RAM4K.hdl
Chen_Tianyang/hw3/RAM512.hdl
Chen_Tianyang/hw3/RAM64.hdl
Chen_Tianyang/hw3/RAM8.hdl
Chen_Tianyang/hw3/Register.hdl

Chen_Tianyang_hw3

---

Maghri_Ahmed/hw3/Bit.hdl
Maghri_Ahmed/hw3/PC.hdl
Maghri_Ahmed/hw3/RAM16K.hdl
Maghri_Ahmed/hw3/RAM4K.hdl
Maghri_Ahmed/hw3/RAM512.hdl
Maghri_Ahmed/hw3/RAM64.hdl
Maghri_Ahmed/hw3/RAM8.hdl
Maghri_Ahmed/hw3/Register.hdl

MAGHRI_Ahmed_hw3

---

Rada_Ylli/hw2/ALU.hdl
Rada_Ylli/hw2/Add16.hdl
Rada_Ylli/hw2/FullAdder.hdl
Rada_Ylli/hw2/HalfAdder.hdl
Rada_Ylli/hw2/Inc16.hdl

Dear Professor,
I hope you are doing well. I wanted to inform you that I have submitted my Homework 2 HDL files and explain why I had to create a new pull request, despite your instruction to avoid doing so unless absolutely necessary.
Initially, I opened a pull request from my main branch, but due to some mistakes in my submission, the merge attempt failed. To solve this, I wiped my main branch clean, synced it with the public repository, and then created a new branch, hw2, where I correctly placed all my homework files under:
Rada_Ylli/hw2/
However, when I revisited my original pull request, I found that it had automatically closed because GitHub detected that there were no changes left to commit (since main was wiped clean). When I attempted to edit the pull request to change the …

Rada_Ylli_hw2

---

Rada_Ylli/hw3/Bit.hdl
Rada_Ylli/hw3/PC.hdl
Rada_Ylli/hw3/RAM16K.hdl
Rada_Ylli/hw3/RAM4K.hdl
Rada_Ylli/hw3/RAM512.hdl
Rada_Ylli/hw3/RAM64.hdl
Rada_Ylli/hw3/RAM8.hdl
Rada_Ylli/hw3/Register.hdl

I added all of the HDL Files for homework 3.

Rada_Ylli_hw3

---

Dragoljevic_Mia/hw3/Bit.hdl
Dragoljevic_Mia/hw3/PC.hdl
Dragoljevic_Mia/hw3/RAM16K.hdl
Dragoljevic_Mia/hw3/RAM4K.hdl
Dragoljevic_Mia/hw3/RAM512.hdl
Dragoljevic_Mia/hw3/RAM64.hdl
Dragoljevic_Mia/hw3/RAM8.hdl
Dragoljevic_Mia/hw3/Register.hdl

my submisson of the third homework.

Dragoljevic_Mia_hw3

---

Mersini_Kiara/hw3/Bit.hdl
Mersini_Kiara/hw3/PC.hdl
Mersini_Kiara/hw3/RAM16K.hdl
Mersini_Kiara/hw3/RAM4K.hdl
Mersini_Kiara/hw3/RAM512.hdl
Mersini_Kiara/hw3/RAM64.hdl
Mersini_Kiara/hw3/RAM8.hdl
Mersini_Kiara/hw3/Register.hdl

Mersini_Kiara_hw3

---

Gatarayiha_Elsa/hw3/Bit.hdl
Gatarayiha_Elsa/hw3/PC.hdl
Gatarayiha_Elsa/hw3/RAM16K.hdl
Gatarayiha_Elsa/hw3/RAM4K.hdl
Gatarayiha_Elsa/hw3/RAM512.hdl
Gatarayiha_Elsa/hw3/RAM64.hdl
Gatarayiha_Elsa/hw3/RAM8.hdl
Gatarayiha_Elsa/hw3/Register.hdl
Gatarayiha_Elsa_HW.txt

Gatarayiha_Elsa_hw3

---

Okumus_Kaan/hw3/Bit.hdl
Okumus_Kaan/hw3/PC.hdl
Okumus_Kaan/hw3/RAM16K.hdl
Okumus_Kaan/hw3/RAM4K.hdl
Okumus_Kaan/hw3/RAM512.hdl
Okumus_Kaan/hw3/RAM64.hdl
Okumus_Kaan/hw3/RAM8.hdl
Okumus_Kaan/hw3/Register.hdl

Adding homework3 / Okumus_Kaan

Okumus_Kaan_hw3

---

Staykova_Margarita/hw3/Bit.hdl
Staykova_Margarita/hw3/PC.hdl
Staykova_Margarita/hw3/RAM16K.hdl
Staykova_Margarita/hw3/RAM4K.hdl
Staykova_Margarita/hw3/RAM512.hdl
Staykova_Margarita/hw3/RAM64.hdl
Staykova_Margarita/hw3/RAM8.hdl
Staykova_Margarita/hw3/Register.hdl

added folder structure for hw3 and respective hdl files

Staykova_Margarita_hw3

---

Nabiyeva_Khadija/hw3/Bit.hdl
Nabiyeva_Khadija/hw3/PC.hdl
Nabiyeva_Khadija/hw3/RAM16K.hdl
Nabiyeva_Khadija/hw3/RAM4K.hdl
Nabiyeva_Khadija/hw3/RAM512.hdl
Nabiyeva_Khadija/hw3/RAM64.hdl
Nabiyeva_Khadija/hw3/RAM8.hdl
Nabiyeva_Khadija/hw3/Register.hdl

Added files for the folder structure

Nabiyeva_Khadija_hw3

---

Hussein_Moaz/hw3/Bit.hdl
Hussein_Moaz/hw3/PC.hdl
Hussein_Moaz/hw3/RAM16K.hdl
Hussein_Moaz/hw3/RAM4K.hdl
Hussein_Moaz/hw3/RAM512.hdl
Hussein_Moaz/hw3/RAM64.hdl
Hussein_Moaz/hw3/RAM8.hdl
Hussein_Moaz/hw3/Register.hdl

Hussein_Moaz_hw3

---

ValdezCastro_AlexisLeonel/hw3/Bit.hdl
ValdezCastro_AlexisLeonel/hw3/PC.hdl
ValdezCastro_AlexisLeonel/hw3/RAM16K.hdl
ValdezCastro_AlexisLeonel/hw3/RAM4K.hdl
ValdezCastro_AlexisLeonel/hw3/RAM512.hdl
ValdezCastro_AlexisLeonel/hw3/RAM64.hdl
ValdezCastro_AlexisLeonel/hw3/RAM8.hdl
ValdezCastro_AlexisLeonel/hw3/Register.hdl

ValdezCastro_AlexisLeonel_hw3

---

Mohammad_Alda/hw3/Bit.hdl
Mohammad_Alda/hw3/PC.hdl
Mohammad_Alda/hw3/RAM16K.hdl
Mohammad_Alda/hw3/RAM4K.hdl
Mohammad_Alda/hw3/RAM512.hdl
Mohammad_Alda/hw3/RAM64.hdl
Mohammad_Alda/hw3/RAM8.hdl
Mohammad_Alda/hw3/Register.hdl

Mohammad_Alda_hw3

---

Huseynli_Suad/hw3/Bit.hdl
Huseynli_Suad/hw3/PC.hdl
Huseynli_Suad/hw3/RAM16K.hdl
Huseynli_Suad/hw3/RAM4K.hdl
Huseynli_Suad/hw3/RAM512.hdl
Huseynli_Suad/hw3/RAM64.hdl
Huseynli_Suad/hw3/RAM8.hdl
Huseynli_Suad/hw3/Register.hdl

Huseynli_Suad_hw3

---

Khanmammadli_Yusif/hw3/Bit.hdl
Khanmammadli_Yusif/hw3/PC.hdl
Khanmammadli_Yusif/hw3/RAM16K.hdl
Khanmammadli_Yusif/hw3/RAM4K.hdl
Khanmammadli_Yusif/hw3/RAM512.hdl
Khanmammadli_Yusif/hw3/RAM64.hdl
Khanmammadli_Yusif/hw3/RAM8.hdl
Khanmammadli_Yusif/hw3/Register.hdl

Khanmammadli_Yusif_hw3

---

Landin_Alexey/hw3/Bit.hdl
Landin_Alexey/hw3/PC.hdl
Landin_Alexey/hw3/RAM16K.hdl
Landin_Alexey/hw3/RAM4K.hdl
Landin_Alexey/hw3/RAM512.hdl
Landin_Alexey/hw3/RAM64.hdl
Landin_Alexey/hw3/RAM8.hdl
Landin_Alexey/hw3/Register.hdl

Hi, my previous pull request was closed due to the fact that I had deleted the hw1 folder. It was closed by you, so I was unable to reopen it, hence I have opened this new pull request with the third homework

Landin_Alexey_hw3

---

Landin_Alexey/hw1/And.hdl
Landin_Alexey/hw1/And16.hdl
Landin_Alexey/hw1/DMux.hdl
Landin_Alexey/hw1/DMux4Way.hdl
Landin_Alexey/hw1/DMux8Way.hdl
Landin_Alexey/hw1/Mux.hdl
Landin_Alexey/hw1/Mux16.hdl
Landin_Alexey/hw1/Mux4Way16.hdl
Landin_Alexey/hw1/Mux8Way16.hdl
Landin_Alexey/hw1/Not.hdl
Landin_Alexey/hw1/Not16.hdl
Landin_Alexey/hw1/Or.hdl
Landin_Alexey/hw1/Or16.hdl
Landin_Alexey/hw1/Or8Way.hdl
Landin_Alexey/hw1/Xor.hdl

Hi, I have accidentally deleted the folder with the first homework, thus I have opened a new request to push it in the main repository one more time. Sorry

Landin_Alexey_hw1

---

Aguero_Alfred/hw4/Fill.asm
Aguero_Alfred/hw4/Mult.asm

Aguero_Alfred_hw4

---

Rada_Ylli/hw4/Fill.asm
Rada_Ylli/hw4/Mult.asm

Added hw4 files to Rada_Ylli/hw4

Rada_Ylli_hw4

---

Mersini_Kiara/hw4/Fill.asm
Mersini_Kiara/hw4/Mult.asm

Mersini_Kiara_hw4

---

Blascu_Elena/hw4/Fill.asm
Blascu_Elena/hw4/Mult.asm

Blascu_Elena_hw4

---

Gherasim_Mihnea/hw4/Fill.asm
Gherasim_Mihnea/hw4/Mult.asm

Gherasim_Mihnea_hw4

---

Bhave_Aneesh/hw4/Fill.asm
Bhave_Aneesh/hw4/Mult.asm

Bhave_Aneesh_hw4

---

Mersini_Keid/hw4/Fill.asm
Mersini_Keid/hw4/Mult.asm

Mersini_Keid_hw4

---

Ibrahim_Joshua/hw4/Fill.asm
Ibrahim_Joshua/hw4/Mult.asm

Joshua Joseph Ragy Ibrahim Hw 4 submission

Ibrahim_Joshua_hw4

---

Staykova_Margarita/hw4/Fill.asm
Staykova_Margarita/hw4/Mult.asm

Staykova_Margarita_hw4

---

Dzangare_Elohim/hw4/Fill.asm
Dzangare_Elohim/hw4/Mult.asm

Dzangare_Elohim_hw4

---

Dzangare_Elohim/hw3/Bit.hdl
Dzangare_Elohim/hw3/PC.hdl
Dzangare_Elohim/hw3/RAM16K.hdl
Dzangare_Elohim/hw3/RAM4K.hdl
Dzangare_Elohim/hw3/RAM512.hdl
Dzangare_Elohim/hw3/RAM64.hdl
Dzangare_Elohim/hw3/RAM8.hdl
Dzangare_Elohim/hw3/Register.hdl

I initially submitted this before the deadline but it was not merged due to an error in the pull request. The original pull request was #559.

Dzangare_Elohim_hw3

---

Nabiyeva_Khadija/hw4/Fill.asm
Nabiyeva_Khadija/hw4/Mult.asm

Khadija_Nabiyeva_hw4

---

Tajani_Khaoula/hw4/Fill.asm
Tajani_Khaoula/hw4/Mult.asm

Tajani_Khaoula_hw4

---

Mersini_Kiara/hw5/CPU.hdl
Mersini_Kiara/hw5/Computer.hdl
Mersini_Kiara/hw5/Memory.hdl

Mersini_Kiara_hw5

---

Maskaj_Endri/hw5/CPU.hdl
Maskaj_Endri/hw5/Computer.hdl
Maskaj_Endri/hw5/Memory.hdl

Maskaj_Endri_hw5

---

Okumus_Kaan/hw5/CPU.hdl
Okumus_Kaan/hw5/Computer.hdl
Okumus_Kaan/hw5/Memory.hdl

Okumus_Kaan_hw5

---

Bashir_Mustafa/hw5/CPU.hdl
Bashir_Mustafa/hw5/Computer.hdl
Bashir_Mustafa/hw5/Memory.hdl

Bashir_Mustafa_hw5

---

Rexhepi_Endi/hw5/CPU.hdl
Rexhepi_Endi/hw5/Computer.hdl
Rexhepi_Endi/hw5/Memory.hdl

Rexhepi_Endi_hw5

---

Dragoljevic_Mia/hw5/CPU.hdl
Dragoljevic_Mia/hw5/Computer.hdl
Dragoljevic_Mia/hw5/Memory.hdl

Dragoljevic_Mia_hw5

---

Stribu_Alicia/hw5/CPU.hdl
Stribu_Alicia/hw5/Computer.hdl
Stribu_Alicia/hw5/Memory.hdl

Stirbu_Alicia_hw5

---

Gherasim_Mihnea/hw5/CPU.hdl
Gherasim_Mihnea/hw5/Computer.hdl
Gherasim_Mihnea/hw5/Memory.hdl

Gherasim_Mihnea_hw5

---

Staykova_Margarita/hw5/CPU.hdl
Staykova_Margarita/hw5/Computer.hdl
Staykova_Margarita/hw5/Memory.hdl

Staykova_Margarita_hw5

---

Sarka_Yilikal/hw5/CPU.hdl
Sarka_Yilikal/hw5/Computer.hdl
Sarka_Yilikal/hw5/Memory.hdl

Sarka_Yilikal_hw5

---

Blascu_Elena/hw5/CPU.hdl
Blascu_Elena/hw5/Computer.hdl
Blascu_Elena/hw5/Memory.hdl

Blascu_Elena_hw5

---

Jalilova_Asiman/hw5/CPU.hdl
Jalilova_Asiman/hw5/Computer.hdl
Jalilova_Asiman/hw5/Memory.hdl

Added folder structure for homeworks.

Jalilova_Asiman_hw5

---

Sacmaci_Furkan/hw5/CPU.hdl
Sacmaci_Furkan/hw5/Computer.hdl
Sacmaci_Furkan/hw5/Memory.hdl

Sacmaci_Furkan_hw5

---

Dzangare_Elohim/hw5/CPU.hdl
Dzangare_Elohim/hw5/Computer.hdl
Dzangare_Elohim/hw5/Memory.hdl

Dzangare_Elohim_hw5

---

Jashari_Redon/hw1/And.hdl
Jashari_Redon/hw1/And16.hdl
Jashari_Redon/hw1/DMux.hdl
Jashari_Redon/hw1/DMux4Way.hdl
Jashari_Redon/hw1/DMux8Way.hdl
Jashari_Redon/hw1/Mux.hdl
Jashari_Redon/hw1/Mux16.hdl
Jashari_Redon/hw1/Mux4Way16.hdl
Jashari_Redon/hw1/Mux8Way16.hdl
Jashari_Redon/hw1/Not.hdl
Jashari_Redon/hw1/Not16.hdl
Jashari_Redon/hw1/Or.hdl
Jashari_Redon/hw1/Or16.hdl
Jashari_Redon/hw1/Or8Way.hdl
Jashari_Redon/hw1/Xor.hdl

Jashari_Redon_hw1

---

Znaien_Mohamed/hw1/And.hdl
Znaien_Mohamed/hw1/And16.hdl
Znaien_Mohamed/hw1/DMux.hdl
Znaien_Mohamed/hw1/DMux4Way.hdl
Znaien_Mohamed/hw1/DMux8Way.hdl
Znaien_Mohamed/hw1/Mux.hdl
Znaien_Mohamed/hw1/Mux16.hdl
Znaien_Mohamed/hw1/Mux4Way16.hdl
Znaien_Mohamed/hw1/Mux8Way16.hdl
Znaien_Mohamed/hw1/Not.hdl
Znaien_Mohamed/hw1/Not16.hdl
Znaien_Mohamed/hw1/Or.hdl
Znaien_Mohamed/hw1/Or16.hdl
Znaien_Mohamed/hw1/Or8Way.hdl
Znaien_Mohamed/hw1/Xor.hdl

I have 44 points in total so I'm reputing my work for hw1 this is the link : mohamed_znaien_hw1 #98

mohamed_znaien_hw1
